In [ ]:
#importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:

df=pd.read_csv('/content/Student Mental health.csv')

In [ ]:
df

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...
96,13/07/2020 19:56:49,Female,21.0,BCS,year 1,3.50 - 4.00,No,No,Yes,No,No
97,13/07/2020 21:21:42,Male,18.0,Engineering,Year 2,3.00 - 3.49,No,Yes,Yes,No,No
98,13/07/2020 21:22:56,Female,19.0,Nursing,Year 3,3.50 - 4.00,Yes,Yes,No,Yes,No
99,13/07/2020 21:23:57,Female,23.0,Pendidikan Islam,year 4,3.50 - 4.00,No,No,No,No,No
100,18/07/2020 20:16:21,Male,20.0,Biomedical science,Year 2,3.00 - 3.49,No,No,No,No,No

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Timestamp                                     101 non-null    object
 1   Choose your gender                            101 non-null    object
 2   Age                                           100 non-null    float64
 3   What is your course?                          101 non-null    object
 4   Your current year of Study                    101 non-null    object
 5   What is your CGPA?                            101 non-null    object
 6   Marital status                                101 non-null    object
 7   Do you have Depression?                       101 non-null    object
 8   Do you have Anxiety?                          101 non-null    object
 9   Do you have Panic attack?                     101 non-null    object
 10  Did you seek any specialist for a treatment?  101 non-null    object
dtypes: float64(1), object(10)
memory usage: 8.8+ KB

In [ ]:
df.describe()

             Age
count  100.00000
mean    20.53000
std      2.49628
min     18.00000
25%     18.00000
50%     19.00000
75%     23.00000
max     24.00000

In [ ]:
df.shape

(101, 11)

In [ ]:
df.head(5)

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
0,8/7/2020 12:02,Female,18.0,Engineering,year 1,3.00 - 3.49,No,Yes,No,Yes,No
1,8/7/2020 12:04,Male,21.0,Islamic education,year 2,3.00 - 3.49,No,No,Yes,No,No
2,8/7/2020 12:05,Male,19.0,BIT,Year 1,3.00 - 3.49,No,Yes,Yes,Yes,No
3,8/7/2020 12:06,Female,22.0,Laws,year 3,3.00 - 3.49,Yes,Yes,No,No,No
4,8/7/2020 12:13,Male,23.0,Mathemathics,year 4,3.00 - 3.49,No,No,No,No,No

In [ ]:
#Finding out the index number whose age is unknown to us
df[df['Age'].isnull()].index

Index([43], dtype='int64')

In [ ]:
# Find record no from 40 to 45
df.iloc[40:46]

,Timestamp,Choose your gender,Age,What is your course?,Your current year of Study,What is your CGPA?,Marital status,Do you have Depression?,Do you have Anxiety?,Do you have Panic attack?,Did you seek any specialist for a treatment?
40,8/7/2020 14:57,Female,24.0,BIT,Year 3,3.00 - 3.49,No,No,Yes,No,No
41,8/7/2020 14:57,Female,22.0,Engineering,year 4,3.50 - 4.00,No,No,No,No,No
42,8/7/2020 14:58,Female,20.0,Usuluddin,year 2,3.00 - 3.49,No,Yes,No,No,No
43,8/7/2020 15:07,Male,NaN,BIT,year 1,0 - 1.99,No,No,No,No,No
44,8/7/2020 15:08,Male,23.0,TAASL,year 2,3.50 - 4.00,No,No,No,Yes,No
45,8/7/2020 15:09,Male,18.0,BCS,year 1,3.50 - 4.00,No,No,Yes,Yes,No

In [ ]:
#Counting Courses which are opted by most of the student
df['Course'] = df['Course'].str.strip()  # Remove extra spaces if any
df['Course'].value_counts()

KeyError: 'Course'

In [ ]:
#Counting number of Female and Male
df['Gender'] = df['Gender'].str.strip().str.capitalize()
df['Gender'].value_counts()

KeyError: 'Gender'

In [ ]:
#Finding Mean Age of Female and Male
df.groupby('Gender')['Age'].mean()

KeyError: 'Gender'

In [ ]:
#Finding Number of Students who are married and not married respectively
df['Marital status'].value_counts()

Marital status
No     85
Yes    16
Name: count, dtype: int64

In [ ]:
#Percentage of students facing depression
(df['Depression'].value_counts(normalize=True) * 100)

KeyError: 'Depression'

In [ ]:
#Percentage of students facing anxiety
(df['Anxiety'].value_counts(normalize=True) * 100)

KeyError: 'Anxiety'

In [ ]:
#percentage of student having panic attacks